//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_NN
    {
        public string APP_CODE { get; set; }
        public string PREFIX_CODE { get; set; }
        public string DOMAIN_CODE { get; set; }
        public string NEXTNUMBER { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
