//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_APPS_ROLES
    {
        public string ROLE_CODE { get; set; }
        public string APP_CODE { get; set; }
        public string NAME { get; set; }
        public string DESC { get; set; }
        public string HOME_URL { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    }
}
