//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_FACILITY
    {
        public string FAC_CODE { get; set; }
        public string FAC_DESC { get; set; }
        public string FAC_ACTIVE { get; set; }
    }
}
