//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_AD_MSTR
    {
        public string addr { get; set; }
        public string name { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string type { get; set; }
        public string attn { get; set; }
        public string phone { get; set; }
        public string ext { get; set; }
        public string @ref { get; set; }
        public string sort { get; set; }
        public string country { get; set; }
        public string attn2 { get; set; }
        public string phone2 { get; set; }
        public string ext2 { get; set; }
        public string fax { get; set; }
        public string fax2 { get; set; }
        public string line3 { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public string lang { get; set; }
        public string pst_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string county { get; set; }
        public Nullable<bool> temp { get; set; }
        public string bk_acct1 { get; set; }
        public string bk_acct2 { get; set; }
        public string format { get; set; }
        public string vat_reg { get; set; }
        public string coc_reg { get; set; }
        public string gst_id { get; set; }
        public string tax_type { get; set; }
        public string taxc { get; set; }
        public Nullable<bool> taxable { get; set; }
        public Nullable<bool> tax_in { get; set; }
        public string conrep { get; set; }
        public string edi_tpid { get; set; }
        public string edi_ctrl { get; set; }
        public string timezone { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string edi_id { get; set; }
        public string barlbl_prt { get; set; }
        public string barlbl_val { get; set; }
        public string calendar { get; set; }
        public string edi_std { get; set; }
        public string edi_level { get; set; }
        public string qad01 { get; set; }
        public string qad02 { get; set; }
        public string qad03 { get; set; }
        public string qad04 { get; set; }
        public string qad05 { get; set; }
        public string chr01 { get; set; }
        public string chr02 { get; set; }
        public string chr03 { get; set; }
        public string chr04 { get; set; }
        public string chr05 { get; set; }
        public string tp_loc_code { get; set; }
        public string ctry { get; set; }
        public string tax_zone { get; set; }
        public string tax_usage { get; set; }
        public string misc1_id { get; set; }
        public string misc2_id { get; set; }
        public string misc3_id { get; set; }
        public string wk_offset { get; set; }
        public string inv_mthd { get; set; }
        public string sch_mthd { get; set; }
        public string po_mthd { get; set; }
        public string asn_data { get; set; }
        public string intr_division { get; set; }
        public bool tax_report { get; set; }
        public string name_control { get; set; }
        public bool last_file { get; set; }
        public string domain { get; set; }
        public string oid_ad_mstr { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public string priority { get; set; }
        public string route { get; set; }
        public string loadseq { get; set; }
        public bool pick_by_date { get; set; }
        public string profile { get; set; }
        public bool tax_in_city { get; set; }
        public string ns_pr_list { get; set; }
        public string address_id { get; set; }
        public string bus_relation { get; set; }
        public string alt_um { get; set; }
        public string city_code { get; set; }
    }
}
