//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SIOP_AMK
    {
        public string DOMAIN { get; set; }
        public string SITE { get; set; }
        public string AMIS { get; set; }
        public string DESC1 { get; set; }
        public string ORDER1 { get; set; }
        public string CUST_PART { get; set; }
        public string SHIP { get; set; }
        public string PART { get; set; }
        public string MASTER_LINE { get; set; }
        public Nullable<decimal> LINE { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public Nullable<decimal> CR_TIME { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> MO_DATE { get; set; }
        public Nullable<decimal> MO_TIME { get; set; }
        public string MO_USER { get; set; }
        public string PO { get; set; }
        public string CUSTREF { get; set; }
        public string MODELYR { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public string CHR05 { get; set; }
        public string CHR06 { get; set; }
        public string CHR07 { get; set; }
        public string CHR08 { get; set; }
        public string CHR09 { get; set; }
        public string CHR10 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public Nullable<decimal> DEC03 { get; set; }
        public Nullable<decimal> DEC04 { get; set; }
        public Nullable<decimal> DEC05 { get; set; }
        public Nullable<decimal> DEC06 { get; set; }
        public Nullable<decimal> DEC07 { get; set; }
        public Nullable<decimal> DEC08 { get; set; }
        public Nullable<decimal> DEC09 { get; set; }
        public Nullable<decimal> DEC10 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public Nullable<System.DateTime> DTE03 { get; set; }
        public Nullable<System.DateTime> DTE04 { get; set; }
        public Nullable<System.DateTime> DTE05 { get; set; }
        public Nullable<System.DateTime> DTE06 { get; set; }
        public Nullable<System.DateTime> DTE07 { get; set; }
        public Nullable<System.DateTime> DTE08 { get; set; }
        public Nullable<System.DateTime> DTE09 { get; set; }
        public Nullable<System.DateTime> DTE10 { get; set; }
        public string LOG01 { get; set; }
        public string LOG02 { get; set; }
        public string LOG03 { get; set; }
        public string LOG04 { get; set; }
        public string LOG05 { get; set; }
        public string LOG06 { get; set; }
        public string LOG07 { get; set; }
        public string LOG08 { get; set; }
        public string LOG09 { get; set; }
        public string LOG10 { get; set; }
        public Nullable<decimal> INT01 { get; set; }
        public Nullable<decimal> INT02 { get; set; }
        public Nullable<decimal> INT03 { get; set; }
        public Nullable<decimal> INT04 { get; set; }
        public Nullable<decimal> INT05 { get; set; }
        public Nullable<decimal> INT06 { get; set; }
        public Nullable<decimal> INT07 { get; set; }
        public Nullable<decimal> INT08 { get; set; }
        public Nullable<decimal> INT09 { get; set; }
        public Nullable<decimal> INT10 { get; set; }
        public decimal OID_AMK_DET { get; set; }
        public Nullable<System.DateTime> RowUpdateDateTime { get; set; }
        public Nullable<System.DateTime> RowCreateDateTime { get; set; }
    }
}
