//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_INVENTORYLOCMASTER
    {
        public string LOC { get; set; }
        public string QAD01 { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public string PERM { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public string PROJECT1 { get; set; }
        public string SITE { get; set; }
        public string STATUS { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string SINGLE1 { get; set; }
        public string TYPE1 { get; set; }
        public string DESC1 { get; set; }
        public Nullable<decimal> CAP { get; set; }
        public string CAP_UM { get; set; }
        public string PHYS_ADDR { get; set; }
        public string XFER_OWNERSHIP { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<decimal> OID_LOC_MSTR { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
