//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_ITEMPLANNING
    {
        public string PART { get; set; }
        public string SITE { get; set; }
        public Nullable<decimal> BATCH { get; set; }
        public string BOM_CODE { get; set; }
        public Nullable<System.DateTime> QAD01 { get; set; }
        public string BUYER { get; set; }
        public Nullable<decimal> CUM_LEAD { get; set; }
        public Nullable<decimal> QAD02 { get; set; }
        public Nullable<decimal> INS_LEAD { get; set; }
        public string INS_RQD { get; set; }
        public string ISS_POL { get; set; }
        public Nullable<decimal> MFG_LEAD { get; set; }
        public string MS { get; set; }
        public Nullable<decimal> ORD_MAX { get; set; }
        public Nullable<decimal> ORD_MIN { get; set; }
        public Nullable<decimal> ORD_MULT { get; set; }
        public Nullable<decimal> ORD_PER { get; set; }
        public string ORD_POL { get; set; }
        public Nullable<decimal> ORD_QTY { get; set; }
        public string PHANTOM { get; set; }
        public string PLAN_ORD { get; set; }
        public string PM_CODE { get; set; }
        public Nullable<decimal> PUR_LEAD { get; set; }
        public string REV { get; set; }
        public Nullable<decimal> ROP { get; set; }
        public string ROUTING { get; set; }
        public Nullable<decimal> RUN { get; set; }
        public Nullable<decimal> RUN_LL { get; set; }
        public Nullable<decimal> SETUP { get; set; }
        public Nullable<decimal> SETUP_LL { get; set; }
        public Nullable<decimal> SFTY_STK { get; set; }
        public Nullable<decimal> SFTY_TME { get; set; }
        public Nullable<decimal> TIMEFNCE { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string VEND { get; set; }
        public Nullable<decimal> YLD_PCT { get; set; }
        public Nullable<decimal> ASSAY { get; set; }
        public string GRADE { get; set; }
        public string NETWORK1 { get; set; }
        public Nullable<decimal> QAD03 { get; set; }
        public Nullable<decimal> QAD04 { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<decimal> QAD05 { get; set; }
        public string DRAW { get; set; }
        public string ECO_PEND { get; set; }
        public Nullable<decimal> LL_BOM { get; set; }
        public string ROLLUP1 { get; set; }
        public string TRANTYPE { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public string CHR05 { get; set; }
        public string CHR06 { get; set; }
        public string CHR07 { get; set; }
        public string CHR08 { get; set; }
        public string CHR09 { get; set; }
        public string CHR10 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public string LOG01 { get; set; }
        public string LOG02 { get; set; }
        public Nullable<decimal> LL_DRP { get; set; }
        public string PO_SITE { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string ROLLUP_ID { get; set; }
        public Nullable<decimal> MFG_PCT { get; set; }
        public Nullable<decimal> PUR_PCT { get; set; }
        public Nullable<decimal> DRP_PCT { get; set; }
        public string POU_CODE { get; set; }
        public Nullable<decimal> WKS_AVG { get; set; }
        public Nullable<decimal> WKS_MAX { get; set; }
        public Nullable<decimal> WKS_MIN { get; set; }
        public Nullable<decimal> PICK_LOGIC { get; set; }
        public string JOINT_TYPE { get; set; }
        public string BTB_TYPE { get; set; }
        public string CFG_TYPE { get; set; }
        public string OP_YIELD { get; set; }
        public string RUN_SEQ1 { get; set; }
        public string RUN_SEQ2 { get; set; }
        public string ATP_ENFORCEMENT { get; set; }
        public string ATP_FAMILY { get; set; }
        public string DOMAIN { get; set; }
        public decimal OID_PTP_DET { get; set; }
        public string INSP_LOC { get; set; }
        public string GCFG_TYPE { get; set; }
        public string REPLENISHMENT_MTHD { get; set; }
        public Nullable<decimal> ATP_HORIZON { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
