//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_PC_MSTR
    {
        public string list { get; set; }
        public string prod_line { get; set; }
        public string part { get; set; }
        public string um { get; set; }
        public System.DateTime start { get; set; }
        public Nullable<System.DateTime> expire { get; set; }
        public string amt_type { get; set; }
        public string desc { get; set; }
        public string min_qty { get; set; }
        public string amt { get; set; }
        public string curr { get; set; }
        public Nullable<bool> tax_in { get; set; }
        public string list_classification { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string min_price { get; set; }
        public string max_price { get; set; }
        public string domain { get; set; }
        public string oid_pc_mstr { get; set; }
        public string qadc01 { get; set; }
        public string qadd01 { get; set; }
    }
}
