//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_FAD_DET
    {
        public string FA_ID { get; set; }
        public string DESC1 { get; set; }
        public string TAG { get; set; }
        public string SERIAL { get; set; }
        public Nullable<decimal> PURAMT { get; set; }
        public string MOD_USERID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string CHR01 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public string LOG01 { get; set; }
        public Nullable<decimal> INT01 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public string QADC01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string QADL01 { get; set; }
        public Nullable<decimal> QADI01 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string DOMAIN { get; set; }
        public decimal OID_FAD_DET { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
    }
}
