//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_FIXEDASSETMASTER
    {
        public string ID1 { get; set; }
        public string ENTITY { get; set; }
        public string POST { get; set; }
        public string DEP { get; set; }
        public string DESC1 { get; set; }
        public string RECEIVER { get; set; }
        public string AUTH_NUMERIC { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string CODE { get; set; }
        public Nullable<System.DateTime> STARTDT { get; set; }
        public Nullable<System.DateTime> WARDT { get; set; }
        public Nullable<System.DateTime> DISP_DT { get; set; }
        public string DISP_RSN { get; set; }
        public Nullable<decimal> PURAMT { get; set; }
        public Nullable<decimal> REPLAMT { get; set; }
        public Nullable<decimal> DISPAMT { get; set; }
        public Nullable<decimal> SALVAMT { get; set; }
        public string CUSTODIAN { get; set; }
        public string FACLS_ID { get; set; }
        public string PARENT1 { get; set; }
        public string VENDSRC { get; set; }
        public string PO { get; set; }
        public string FABCH_ID { get; set; }
        public Nullable<decimal> CMTINDX { get; set; }
        public string INS_CO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public string INS_NBR { get; set; }
        public Nullable<decimal> INSAMT { get; set; }
        public string MIGRATE1 { get; set; }
        public string MOD_USERID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public Nullable<decimal> DEC03 { get; set; }
        public Nullable<decimal> DEC04 { get; set; }
        public string LOG01 { get; set; }
        public string LOG02 { get; set; }
        public string LOG03 { get; set; }
        public string LOG04 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public Nullable<System.DateTime> DTE03 { get; set; }
        public Nullable<System.DateTime> DTE04 { get; set; }
        public Nullable<decimal> INT01 { get; set; }
        public Nullable<decimal> INT02 { get; set; }
        public Nullable<decimal> INT03 { get; set; }
        public Nullable<decimal> INT04 { get; set; }
        public string QADC01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string QADL01 { get; set; }
        public Nullable<decimal> QADI01 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string SPLIT_FROM { get; set; }
        public Nullable<System.DateTime> SPLIT_DATE { get; set; }
        public string FALOC_ID { get; set; }
        public string QADC02 { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<decimal> OID_FA_MSTR { get; set; }
        public string ACQ_POST { get; set; }
        public Nullable<decimal> POSTED_PURAMT { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
