//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_UM
    {
        public string um_um { get; set; }
        public string um_alt_um { get; set; }
        public string um_conv { get; set; }
        public string um_part { get; set; }
        public string um_desc { get; set; }
        public string um_alt_qty { get; set; }
        public string um_decimals { get; set; }
        public string um_user1 { get; set; }
        public string um_user2 { get; set; }
        public string um__chr01 { get; set; }
        public string um__chr02 { get; set; }
        public string um__chr03 { get; set; }
        public string um__chr04 { get; set; }
        public string um__chr05 { get; set; }
        public string um__chr06 { get; set; }
        public string um__dec01 { get; set; }
        public string um__dec02 { get; set; }
        public Nullable<System.DateTime> um__dte01 { get; set; }
        public Nullable<System.DateTime> um__dte02 { get; set; }
        public Nullable<bool> um__log01 { get; set; }
        public Nullable<bool> um__log02 { get; set; }
        public string um_domain { get; set; }
        public string oid_um_mstr { get; set; }
    }
}
