//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_CustomerShipTo
    {
        public string DebtorShipTo_ID { get; set; }
        public string Address_ID { get; set; }
        public string Debtor_ID { get; set; }
        public string SharedSet_ID { get; set; }
        public string DebtorEndUser_ID { get; set; }
        public string DebtorShipToCode { get; set; }
        public bool DebtorShipToIsDebtor { get; set; }
        public string CustomShort0 { get; set; }
        public string CustomShort1 { get; set; }
        public string CustomShort2 { get; set; }
        public string CustomShort3 { get; set; }
        public string CustomShort4 { get; set; }
        public string CustomShort5 { get; set; }
        public string CustomShort6 { get; set; }
        public string CustomShort7 { get; set; }
        public string CustomShort8 { get; set; }
        public string CustomShort9 { get; set; }
        public string CustomCombo0 { get; set; }
        public string CustomCombo1 { get; set; }
        public string CustomCombo2 { get; set; }
        public string CustomCombo3 { get; set; }
        public string CustomCombo4 { get; set; }
        public string CustomCombo5 { get; set; }
        public string CustomCombo6 { get; set; }
        public string CustomCombo7 { get; set; }
        public string CustomCombo8 { get; set; }
        public string CustomCombo9 { get; set; }
        public string CustomLong0 { get; set; }
        public string CustomLong1 { get; set; }
        public string CustomNote { get; set; }
        public Nullable<System.DateTime> CustomDate0 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public string CustomInteger0 { get; set; }
        public string CustomInteger1 { get; set; }
        public string CustomInteger2 { get; set; }
        public string CustomInteger3 { get; set; }
        public string CustomInteger4 { get; set; }
        public string CustomDecimal0 { get; set; }
        public string CustomDecimal1 { get; set; }
        public string CustomDecimal2 { get; set; }
        public string CustomDecimal3 { get; set; }
        public string CustomDecimal4 { get; set; }
        public string DebtorShipToName { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string QADD01 { get; set; }
    }
}
