//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_DEBTOR
    {
        public int Debtor_ID { get; set; }
        public int SharedSet_ID { get; set; }
        public int InvControlGLProfile_ID { get; set; }
        public int CnControlGLProfile_ID { get; set; }
        public Nullable<int> FinChgGLProfile_ID { get; set; }
        public int NormalPaymentCondition_ID { get; set; }
        public int BusinessRelation_ID { get; set; }
        public int Currency_ID { get; set; }
        public Nullable<int> DivisionProfile_ID { get; set; }
        public Nullable<int> SalesCode_ID { get; set; }
        public string VatDeliveryType { get; set; }
        public int Reason_ID { get; set; }
        public Nullable<int> BLWIGroup_ID { get; set; }
        public Nullable<int> DeliveryCond_ID { get; set; }
        public Nullable<int> PaymentGroup_ID { get; set; }
        public Nullable<int> ObsoletePreInvGroup_ID { get; set; }
        public int SalesAccountGLProfile_ID { get; set; }
        public Nullable<int> BillToDebtor_ID { get; set; }
        public Nullable<int> DebtorType_ID { get; set; }
        public Nullable<int> DebtorCreditRating_ID { get; set; }
        public int PrePayControlGLProfile_ID { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorIsActive { get; set; }
        public string VatPercentageLevel { get; set; }
        public string DebtorIsPrintStatement { get; set; }
        public string DebtorIsPrintReminder { get; set; }
        public Nullable<int> DomiciliationNumber { get; set; }
        public string DebtorIsTaxable { get; set; }
        public string DebtorIsTaxInCity { get; set; }
        public string DebtorIsTaxIncluded { get; set; }
        public string DebtorTaxIDFederal { get; set; }
        public string DebtorTaxIDState { get; set; }
        public string DebtorTaxIDMisc1 { get; set; }
        public string DebtorTaxIDMisc2 { get; set; }
        public string DebtorTaxIDMisc3 { get; set; }
        public Nullable<int> DebtorTaxDeclaration { get; set; }
        public string DebtorIsFixedCredLim { get; set; }
        public Nullable<decimal> DebtorFixedCredLimTC { get; set; }
        public string DebtorIsTurnOverCredLim { get; set; }
        public Nullable<decimal> DebtorPercTurnOverCredLim { get; set; }
        public string DebtorIsMaxDaysDueCredLim { get; set; }
        public Nullable<int> DebtorMaxNumDaysCredLim { get; set; }
        public string DebtorIsInclOpenItmCredLim { get; set; }
        public string ObsoleteInclPreInvCredLim { get; set; }
        public string DebtorIsInclSOCredLim { get; set; }
        public string DebtorIsInclDraftCredLim { get; set; }
        public string DebtorIsCheckBefSOCredLim { get; set; }
        public string DebtorIsCheckAftSOCredLim { get; set; }
        public string ObsoleteCheckBefPICredLim { get; set; }
        public string ObsoleteCheckAftPICredLim { get; set; }
        public string DebtorIsCheckBefDICredLim { get; set; }
        public string DebtorIsCheckAftDICredLim { get; set; }
        public Nullable<decimal> DebtorPercWarningCredLim { get; set; }
        public string DebtorIsOverruleSOCredLim { get; set; }
        public string ObsoleteOverrulePICredLim { get; set; }
        public string DebtorIsOverruleDICredLim { get; set; }
        public string DebtorIsLockedCredLim { get; set; }
        public string DebtorIsToBeLockedCredLim { get; set; }
        public string DebtorIsWithPreInvGroup { get; set; }
        public string ObsoleteGroupingSOOnPreInv { get; set; }
        public string DebtorIsInvoiceByAuth { get; set; }
        public string DebtorDBNumber { get; set; }
        public string DebtorIsFinanceCharge { get; set; }
        public string DebtorStatementCycle { get; set; }
        public Nullable<System.DateTime> DebtorLastPayment { get; set; }
        public Nullable<System.DateTime> DebtorLastSale { get; set; }
        public Nullable<decimal> DebtorHighCredit { get; set; }
        public Nullable<System.DateTime> DebtorHighCreditDate { get; set; }
        public Nullable<System.DateTime> DebtorLastCreditReview { get; set; }
        public Nullable<System.DateTime> DebtorLastCreditUpdate { get; set; }
        public string DebtorCommentNote { get; set; }
        public Nullable<decimal> DebtorSalesOrderBalance { get; set; }
        public Nullable<System.DateTime> DebtorLastFinChargeDate { get; set; }
        public Nullable<int> DebtorTotalDaysLate { get; set; }
        public Nullable<int> DebtorTotalNbrOfInvoices { get; set; }
        public string TxzTaxZone { get; set; }
        public string TxclTaxCls { get; set; }
        public string TxuTaxUsage { get; set; }
        public string CustomShort0 { get; set; }
        public string CustomShort1 { get; set; }
        public string CustomShort2 { get; set; }
        public string CustomShort3 { get; set; }
        public string CustomShort4 { get; set; }
        public string CustomShort5 { get; set; }
        public string CustomShort6 { get; set; }
        public string CustomShort7 { get; set; }
        public string CustomShort8 { get; set; }
        public string CustomShort9 { get; set; }
        public string CustomCombo0 { get; set; }
        public string CustomCombo1 { get; set; }
        public string CustomCombo2 { get; set; }
        public string CustomCombo3 { get; set; }
        public string CustomCombo4 { get; set; }
        public string CustomCombo5 { get; set; }
        public string CustomCombo6 { get; set; }
        public string CustomCombo7 { get; set; }
        public string CustomCombo8 { get; set; }
        public string CustomCombo9 { get; set; }
        public string CustomLong0 { get; set; }
        public string CustomLong1 { get; set; }
        public string CustomNote { get; set; }
        public Nullable<System.DateTime> CustomDate0 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public Nullable<int> CustomInteger0 { get; set; }
        public Nullable<int> CustomInteger1 { get; set; }
        public Nullable<int> CustomInteger2 { get; set; }
        public Nullable<int> CustomInteger3 { get; set; }
        public Nullable<int> CustomInteger4 { get; set; }
        public Nullable<decimal> CustomDecimal0 { get; set; }
        public Nullable<decimal> CustomDecimal1 { get; set; }
        public Nullable<decimal> CustomDecimal2 { get; set; }
        public Nullable<decimal> CustomDecimal3 { get; set; }
        public Nullable<decimal> CustomDecimal4 { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedTime { get; set; }
        public string LastModifiedUser { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public Nullable<int> DeductionCtrlGLProfile_ID { get; set; }
        public string CustomShort10 { get; set; }
        public string CustomShort11 { get; set; }
        public string CustomShort12 { get; set; }
        public string CustomShort13 { get; set; }
        public string CustomShort14 { get; set; }
        public string CustomShort15 { get; set; }
        public string CustomShort16 { get; set; }
        public string CustomShort17 { get; set; }
        public string CustomShort18 { get; set; }
        public string CustomShort19 { get; set; }
        public string CustomCombo10 { get; set; }
        public string CustomCombo11 { get; set; }
        public string CustomCombo12 { get; set; }
        public string CustomCombo13 { get; set; }
        public string CustomCombo14 { get; set; }
        public Nullable<decimal> CustomDecimal5 { get; set; }
        public Nullable<decimal> CustomDecimal6 { get; set; }
        public Nullable<decimal> CustomDecimal7 { get; set; }
        public Nullable<decimal> CustomDecimal8 { get; set; }
        public Nullable<decimal> CustomDecimal9 { get; set; }
        public Nullable<System.DateTime> CustomDate5 { get; set; }
        public Nullable<System.DateTime> CustomDate6 { get; set; }
        public Nullable<System.DateTime> CustomDate7 { get; set; }
        public Nullable<System.DateTime> CustomDate8 { get; set; }
        public Nullable<System.DateTime> CustomDate9 { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
