//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SupplierView
    {
        public string Creditor_ID { get; set; }
        public string NormalPaymentCondition_ID { get; set; }
        public string BusinessRelation_ID { get; set; }
        public bool CreditorIsActive { get; set; }
        public string SharedSet_ID { get; set; }
        public string InvControlGLProfile_ID { get; set; }
        public string CnControlGLProfile_ID { get; set; }
        public string DivisionProfile_ID { get; set; }
        public string PurchaseCode_ID { get; set; }
        public string Reason_ID { get; set; }
        public string BLWIGroup_ID { get; set; }
        public string DeliveryCond_ID { get; set; }
        public string Currency_ID { get; set; }
        public string PaymentGroup_ID { get; set; }
        public string PurchaseGLProfile_ID { get; set; }
        public string CreditorType_ID { get; set; }
        public string PurchaseType_ID { get; set; }
        public string PrePayControlGLProfile_ID { get; set; }
        public string CreditorCode { get; set; }
        public string VatDeliveryType { get; set; }
        public string VatPercentageLevel { get; set; }
        public bool CreditorIsSendRemittance { get; set; }
        public bool CreditorIsIndividualPaymnt { get; set; }
        public Nullable<bool> CreditorIsTaxable { get; set; }
        public Nullable<bool> CreditorIsTaxInCity { get; set; }
        public bool CreditorIsTaxIncluded { get; set; }
        public string CreditorTaxIDFederal { get; set; }
        public string CreditorTaxIDState { get; set; }
        public string CreditorTaxIDMisc1 { get; set; }
        public string CreditorTaxIDMisc2 { get; set; }
        public string CreditorTaxIDMisc3 { get; set; }
        public string CreditorTaxDeclaration { get; set; }
        public bool CreditorIsTaxReport { get; set; }
        public string CreditorDBNumber { get; set; }
        public string CreditorCocNumber { get; set; }
        public string CreditorTIDNotice { get; set; }
        public string CreditorDebtorNumber { get; set; }
        public bool CreditorIsTaxConfirmed { get; set; }
        public string CreditorCommentNote { get; set; }
        public string TxzTaxZone { get; set; }
        public string TxclTaxCls { get; set; }
        public string TxuTaxUsage { get; set; }
        public string CustomShort0 { get; set; }
        public string CustomShort1 { get; set; }
        public string CustomShort2 { get; set; }
        public string CustomShort3 { get; set; }
        public string CustomShort4 { get; set; }
        public string CustomShort5 { get; set; }
        public string CustomShort6 { get; set; }
        public string CustomShort7 { get; set; }
        public string CustomShort8 { get; set; }
        public string CustomShort9 { get; set; }
        public string CustomCombo0 { get; set; }
        public string CustomCombo1 { get; set; }
        public string CustomCombo2 { get; set; }
        public string CustomCombo3 { get; set; }
        public string CustomCombo4 { get; set; }
        public string CustomCombo5 { get; set; }
        public string CustomCombo6 { get; set; }
        public string CustomCombo7 { get; set; }
        public string CustomCombo8 { get; set; }
        public string CustomCombo9 { get; set; }
        public string CustomLong0 { get; set; }
        public string CustomLong1 { get; set; }
        public string CustomNote { get; set; }
        public Nullable<System.DateTime> CustomDate0 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public string CustomInteger0 { get; set; }
        public string CustomInteger1 { get; set; }
        public string CustomInteger2 { get; set; }
        public string CustomInteger3 { get; set; }
        public string CustomInteger4 { get; set; }
        public string CustomDecimal0 { get; set; }
        public string CustomDecimal1 { get; set; }
        public string CustomDecimal2 { get; set; }
        public string CustomDecimal3 { get; set; }
        public string CustomDecimal4 { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedTime { get; set; }
        public string LastModifiedUser { get; set; }
        public string WHTCertFormat_ID { get; set; }
        public bool CreditorIsWHT { get; set; }
        public string CreditorTaxIDFiscalCode { get; set; }
        public string CreditorForeignFiscalCode { get; set; }
        public Nullable<System.DateTime> CreditorBirthDate { get; set; }
        public string CreditorBirthCity { get; set; }
        public string FinChgGLProfile_ID { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string QADD01 { get; set; }
        public string CustomShort10 { get; set; }
        public string CustomShort11 { get; set; }
        public string CustomShort12 { get; set; }
        public string CustomShort13 { get; set; }
        public string CustomShort14 { get; set; }
        public string CustomShort15 { get; set; }
        public string CustomShort16 { get; set; }
        public string CustomShort17 { get; set; }
        public string CustomShort18 { get; set; }
        public string CustomShort19 { get; set; }
        public string CustomCombo10 { get; set; }
        public string CustomCombo11 { get; set; }
        public string CustomCombo12 { get; set; }
        public string CustomCombo13 { get; set; }
        public string CustomCombo14 { get; set; }
        public string CustomDecimal5 { get; set; }
        public string CustomDecimal6 { get; set; }
        public string CustomDecimal7 { get; set; }
        public string CustomDecimal8 { get; set; }
        public string CustomDecimal9 { get; set; }
        public Nullable<System.DateTime> CustomDate5 { get; set; }
        public Nullable<System.DateTime> CustomDate6 { get; set; }
        public Nullable<System.DateTime> CustomDate7 { get; set; }
        public Nullable<System.DateTime> CustomDate8 { get; set; }
        public Nullable<System.DateTime> CustomDate9 { get; set; }
    }
}
