//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_LS_CustomerShipTo
    {
        public string DOMAIN { get; set; }
        public string TYPE { get; set; }
        public string addr { get; set; }
        public string NAME { get; set; }
    }
}
