//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_VDMASTER
    {
        public string ADDR { get; set; }
        public string CR_TERMS { get; set; }
        public string BUYER { get; set; }
        public Nullable<decimal> DISC_PCT { get; set; }
        public string SHIPVIA { get; set; }
        public string PARTIAL { get; set; }
        public string RMKS { get; set; }
        public string AP_ACCT { get; set; }
        public string AP_CC { get; set; }
        public string PUR_ACCT { get; set; }
        public string PUR_CC { get; set; }
        public string PUR_CNTCT { get; set; }
        public string AP_CNTCT { get; set; }
        public string VD_1099 { get; set; }
        public string SORT1 { get; set; }
        public Nullable<System.DateTime> LAST_CK { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string HOLD { get; set; }
        public string TAX_ID { get; set; }
        public string TAXABLE { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string CURR { get; set; }
        public string LANG { get; set; }
        public string VT_ID { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public string CHR05 { get; set; }
        public string CHR06 { get; set; }
        public string CHR07 { get; set; }
        public string CHR08 { get; set; }
        public string CHR09 { get; set; }
        public string CHR10 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public string LOG01 { get; set; }
        public string FOB { get; set; }
        public string DEBTOR { get; set; }
        public string BANK { get; set; }
        public string CKFRM { get; set; }
        public string PAY_SPEC { get; set; }
        public string REMIT { get; set; }
        public string TYPE1 { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public Nullable<decimal> PREPAY { get; set; }
        public string CONREP_LOGIC { get; set; }
        public string PR_LIST { get; set; }
        public Nullable<decimal> DRFT_BAL { get; set; }
        public Nullable<decimal> LC_BAL { get; set; }
        public string PR_LIST2 { get; set; }
        public string FIX_PR { get; set; }
        public string FR_LIST { get; set; }
        public Nullable<decimal> FR_MIN_WT { get; set; }
        public string FR_TERMS { get; set; }
        public string TID_NOTICE { get; set; }
        public string PROMO { get; set; }
        public string MISC_CR { get; set; }
        public string RCV_SO_PRICE { get; set; }
        public string RCV_HELD_SO { get; set; }
        public string TP_USE_PCT { get; set; }
        public Nullable<decimal> TP_PCT { get; set; }
        public string EX_RATETYPE { get; set; }
        public string DB { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public string QADC03 { get; set; }
        public string QADC04 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public Nullable<decimal> QADD02 { get; set; }
        public string QADL01 { get; set; }
        public string QADL02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<System.DateTime> QADT02 { get; set; }
        public Nullable<decimal> QADI01 { get; set; }
        public Nullable<decimal> QADI02 { get; set; }
        public string QADL03 { get; set; }
        public string QADL04 { get; set; }
        public string AP_SUB { get; set; }
        public string PUR_SUB { get; set; }
        public string TOT_TERMS_CODE { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<decimal> OID_VD_MSTR { get; set; }
        public string CARRIER_ID { get; set; }
        public string KANBAN_SUPPLIER { get; set; }
        public Nullable<decimal> OID_BTR_MSTR { get; set; }
        public string ACTIVE { get; set; }
        public string DATA_COMPLETE { get; set; }
        public string TAX_ZONE { get; set; }
        public string TAXC { get; set; }
        public string TAX_USAGE { get; set; }
        public string GST_ID { get; set; }
        public string PST_ID { get; set; }
        public string MISC1_ID { get; set; }
        public string MISC2_ID { get; set; }
        public string MISC3_ID { get; set; }
        public string TAX_IN { get; set; }
        public string TAX_IN_CITY { get; set; }
        public string DAYBOOKSET { get; set; }
        public string SITE { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
    }
}
