//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_ITEMPACKAGING
    {
        public string SITE { get; set; }
        public string PART { get; set; }
        public string CARTON_TYPE { get; set; }
        public Nullable<decimal> CARTON_L { get; set; }
        public Nullable<decimal> CARTON_W { get; set; }
        public Nullable<decimal> CARTON_H { get; set; }
        public Nullable<decimal> CARTON_CBM { get; set; }
        public Nullable<decimal> CARTON_WEIGHT { get; set; }
        public string CARTON_DIMUM { get; set; }
        public string CARTON_CBMUM { get; set; }
        public string CARTON_WEIGHTUM { get; set; }
        public string PALL_TYPE { get; set; }
        public Nullable<decimal> PALL_WEIGHT { get; set; }
        public string PALL_UM { get; set; }
        public Nullable<decimal> NUM_CARLAY { get; set; }
        public Nullable<decimal> NUM_CARPALL { get; set; }
        public Nullable<decimal> NUM_LAYPALL { get; set; }
        public Nullable<decimal> NUM_ITEMPALL { get; set; }
        public Nullable<decimal> PALL_L { get; set; }
        public Nullable<decimal> PALL_W { get; set; }
        public Nullable<decimal> PALL_H { get; set; }
        public string PALL_DIMUM { get; set; }
        public Nullable<decimal> PALL_FULLL { get; set; }
        public Nullable<decimal> PALL_FULLW { get; set; }
        public Nullable<decimal> PALL_FULLH { get; set; }
        public string PALL_FULLUM { get; set; }
        public Nullable<decimal> PALL_FULLCBM { get; set; }
        public string PALL_CBMUM { get; set; }
        public Nullable<decimal> PALL_FULLWEIGHT { get; set; }
        public string FULL_WEIGHTUM { get; set; }
        public string FIXLOC { get; set; }
        public string DOMAIN { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public string CHR05 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public Nullable<decimal> DEC03 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public string LOG01 { get; set; }
        public string LOG02 { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USERID { get; set; }
        public Nullable<decimal> SNP { get; set; }
        public string DG_CALSS { get; set; }
        public string UN_CODE { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
