//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_ITEMCOST
    {
        public string SIM { get; set; }
        public string PART { get; set; }
        public Nullable<decimal> CST_TOT { get; set; }
        public Nullable<decimal> MTL_TL { get; set; }
        public Nullable<decimal> LBR_TL { get; set; }
        public Nullable<decimal> BDN_TL { get; set; }
        public Nullable<decimal> OVH_TL { get; set; }
        public Nullable<decimal> SUB_TL { get; set; }
        public Nullable<decimal> MTL_LL { get; set; }
        public Nullable<decimal> LBR_LL { get; set; }
        public Nullable<decimal> BDN_LL { get; set; }
        public Nullable<decimal> OVH_LL { get; set; }
        public Nullable<decimal> SUB_LL { get; set; }
        public Nullable<System.DateTime> CST_DATE { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string SERIAL { get; set; }
        public string SITE { get; set; }
        public string ROLLUP1 { get; set; }
        public string ROLLUP_ID { get; set; }
        public Nullable<decimal> NRV { get; set; }
        public string QADC01 { get; set; }
        public string COST_CHANGED { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<decimal> OID_ITEMCOST { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
