//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SCHD_DET
    {
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string schd_type { get; set; }
        public string schd_nbr { get; set; }
        public string schd_line { get; set; }
        public string schd_rlse_id { get; set; }
        public System.DateTime schd_date { get; set; }
        public string schd_time { get; set; }
        public string schd_upd_qty { get; set; }
        public string schd_discr_qty { get; set; }
        public string schd_fc_qual { get; set; }
        public string schd_interval { get; set; }
        public string schd_cum_qty { get; set; }
        public string schd_cmtindx { get; set; }
        public string schd__chr01 { get; set; }
        public string schd__chr02 { get; set; }
        public string schd__chr03 { get; set; }
        public string schd__chr04 { get; set; }
        public string schd__chr05 { get; set; }
        public string schd__chr06 { get; set; }
        public string schd__chr07 { get; set; }
        public string schd__chr08 { get; set; }
        public string schd__chr09 { get; set; }
        public string schd__chr10 { get; set; }
        public string schd__dec01 { get; set; }
        public string schd__dec02 { get; set; }
        public string schd__dec03 { get; set; }
        public string schd__dec04 { get; set; }
        public string schd__dec05 { get; set; }
        public string schd__dec06 { get; set; }
        public string schd__dec07 { get; set; }
        public string schd__dec08 { get; set; }
        public string schd__dec09 { get; set; }
        public string schd__dec10 { get; set; }
        public Nullable<System.DateTime> schd__dte01 { get; set; }
        public Nullable<System.DateTime> schd__dte02 { get; set; }
        public Nullable<bool> schd__log01 { get; set; }
        public Nullable<bool> schd__log02 { get; set; }
        public string schd_user1 { get; set; }
        public string schd_user2 { get; set; }
        public string schd_ship_qty { get; set; }
        public string schd_reference { get; set; }
        public string schd_all_qty { get; set; }
        public Nullable<System.DateTime> schd_per_date { get; set; }
        public string schd_reference_type { get; set; }
        public string schd_domain { get; set; }
        public string oid_schd_det { get; set; }
        public string schd_req_type { get; set; }
    }
}
