//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SIOP_AVS_DET
    {
        public string DOMAIN { get; set; }
        public string SITE { get; set; }
        public string AMIS { get; set; }
        public string CUST { get; set; }
        public string CUST_PART { get; set; }
        public string ORDER1 { get; set; }
        public Nullable<decimal> LINE { get; set; }
        public string PART { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public string SYS_CAL { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public Nullable<decimal> CR_TIME { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> MO_DATE { get; set; }
        public Nullable<decimal> MO_TIME { get; set; }
        public string MO_USER { get; set; }
        public string PO { get; set; }
        public string CUSTREF { get; set; }
        public string MODELYR { get; set; }
        public string CHR01 { get; set; }
        public string CHR02 { get; set; }
        public string CHR03 { get; set; }
        public string CHR04 { get; set; }
        public string CHR05 { get; set; }
        public Nullable<decimal> DEC01 { get; set; }
        public Nullable<decimal> DEC02 { get; set; }
        public Nullable<decimal> DEC03 { get; set; }
        public Nullable<decimal> DEC04 { get; set; }
        public Nullable<decimal> DEC05 { get; set; }
        public Nullable<System.DateTime> DTE01 { get; set; }
        public Nullable<System.DateTime> DTE02 { get; set; }
        public Nullable<System.DateTime> DTE03 { get; set; }
        public Nullable<System.DateTime> DTE04 { get; set; }
        public Nullable<System.DateTime> DTE05 { get; set; }
        public string LOG01 { get; set; }
        public string LOG02 { get; set; }
        public string LOG03 { get; set; }
        public string LOG04 { get; set; }
        public string LOG05 { get; set; }
        public Nullable<decimal> INT01 { get; set; }
        public Nullable<decimal> INT02 { get; set; }
        public Nullable<decimal> INT03 { get; set; }
        public Nullable<decimal> INT04 { get; set; }
        public Nullable<decimal> INT05 { get; set; }
        public decimal OID_AVS_DET { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
    }
}
