//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_GL
    {
        public string GL_ID { get; set; }
        public string SharedSet_ID { get; set; }
        public string BusinessRelation_ID { get; set; }
        public string Currency_ID { get; set; }
        public string BudgetGroup_ID { get; set; }
        public string Unit_ID { get; set; }
        public string CostCentreProfile_ID { get; set; }
        public string ProjectProfile_ID { get; set; }
        public string DivisionProfile_ID { get; set; }
        public string CashInJournalProfile_ID { get; set; }
        public string CashOutJournalProfile_ID { get; set; }
        public string RevalExchangeRateType_ID { get; set; }
        public string RevalCCExchangeRateType_ID { get; set; }
        public string BankJournalProfile_ID { get; set; }
        public string BankDiscountGL_ID { get; set; }
        public string RevaluationGL_ID { get; set; }
        public string CashGroup_ID { get; set; }
        public string UsrDefExchangeRateType_ID { get; set; }
        public string BankARDiscountGL_ID { get; set; }
        public string BankAPDiscountGL_ID { get; set; }
        public string GLAnalysisSetOnByUsr_ID { get; set; }
        public string GLDivisionSetOnByUsr_ID { get; set; }
        public string GLCode { get; set; }
        public string GLDescription { get; set; }
        public string GLTypeCode { get; set; }
        public bool GLIsProjectAccount { get; set; }
        public bool GLIsCostCentreAccount { get; set; }
        public bool GLIsDivisionAccount { get; set; }
        public bool GLIsIntercoAccount { get; set; }
        public bool GLIsQuantityAccount { get; set; }
        public bool GLIsBalanceAccount { get; set; }
        public bool GLIsLocalCurrency { get; set; }
        public Nullable<bool> GLIsSafAccount { get; set; }
        public bool GLIsWithBudget { get; set; }
        public bool GLIsActive { get; set; }
        public bool GLIsDebitAccount { get; set; }
        public bool GLIsAutomaticAccount { get; set; }
        public Nullable<bool> GLIsFixedInterco { get; set; }
        public bool GLIsValueDate { get; set; }
        public string GLRevaluationMethod { get; set; }
        public string GLRevaluationCCMethod { get; set; }
        public string GLExchangeMethod { get; set; }
        public string GLSystemTypeCode { get; set; }
        public string GLAnalysisLimitation { get; set; }
        public string GLCategory { get; set; }
        public Nullable<System.DateTime> GLAnalysisSetOnOnDate { get; set; }
        public Nullable<System.DateTime> GLDivisionSetOnOnDate { get; set; }
        public string CustomShort0 { get; set; }
        public string CustomShort1 { get; set; }
        public string CustomShort2 { get; set; }
        public string CustomShort3 { get; set; }
        public string CustomShort4 { get; set; }
        public string CustomShort5 { get; set; }
        public string CustomShort6 { get; set; }
        public string CustomShort7 { get; set; }
        public string CustomShort8 { get; set; }
        public string CustomShort9 { get; set; }
        public string CustomCombo0 { get; set; }
        public string CustomCombo1 { get; set; }
        public string CustomCombo2 { get; set; }
        public string CustomCombo3 { get; set; }
        public string CustomCombo4 { get; set; }
        public string CustomCombo5 { get; set; }
        public string CustomCombo6 { get; set; }
        public string CustomCombo7 { get; set; }
        public string CustomCombo8 { get; set; }
        public string CustomCombo9 { get; set; }
        public string CustomLong0 { get; set; }
        public string CustomLong1 { get; set; }
        public string CustomNote { get; set; }
        public Nullable<System.DateTime> CustomDate0 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public string CustomInteger0 { get; set; }
        public string CustomInteger1 { get; set; }
        public string CustomInteger2 { get; set; }
        public string CustomInteger3 { get; set; }
        public string CustomInteger4 { get; set; }
        public string CustomDecimal0 { get; set; }
        public string CustomDecimal1 { get; set; }
        public string CustomDecimal2 { get; set; }
        public string CustomDecimal3 { get; set; }
        public string CustomDecimal4 { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedTime { get; set; }
        public string LastModifiedUser { get; set; }
        public string Report2BudgetGroup_ID { get; set; }
        public string Report3BudgetGroup_ID { get; set; }
        public string Report4BudgetGroup_ID { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string QADD01 { get; set; }
        public string BankARInterestGL_ID { get; set; }
        public string BankAPInterestGL_ID { get; set; }
        public string DeductionJournalProfile_ID { get; set; }
        public string CustomShort10 { get; set; }
        public string CustomShort11 { get; set; }
        public string CustomShort12 { get; set; }
        public string CustomShort13 { get; set; }
        public string CustomShort14 { get; set; }
        public string CustomShort15 { get; set; }
        public string CustomShort16 { get; set; }
        public string CustomShort17 { get; set; }
        public string CustomShort18 { get; set; }
        public string CustomShort19 { get; set; }
        public string CustomCombo10 { get; set; }
        public string CustomCombo11 { get; set; }
        public string CustomCombo12 { get; set; }
        public string CustomCombo13 { get; set; }
        public string CustomCombo14 { get; set; }
    }
}
