//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SAF
    {
        public decimal SAF_ID { get; set; }
        public Nullable<decimal> SAFCONCEPT_ID { get; set; }
        public Nullable<decimal> BUDGETGROUP_ID { get; set; }
        public string SAFCODE { get; set; }
        public string SAFDESCRIPTION { get; set; }
        public string SAFISACTIVE { get; set; }
        public string CUSTOMSHORT0 { get; set; }
        public string CUSTOMSHORT1 { get; set; }
        public string CUSTOMSHORT2 { get; set; }
        public string CUSTOMSHORT3 { get; set; }
        public string CUSTOMSHORT4 { get; set; }
        public string CUSTOMSHORT5 { get; set; }
        public string CUSTOMSHORT6 { get; set; }
        public string CUSTOMSHORT7 { get; set; }
        public string CUSTOMSHORT8 { get; set; }
        public string CUSTOMSHORT9 { get; set; }
        public string CUSTOMCOMBO0 { get; set; }
        public string CUSTOMCOMBO1 { get; set; }
        public string CUSTOMCOMBO2 { get; set; }
        public string CUSTOMCOMBO3 { get; set; }
        public string CUSTOMCOMBO4 { get; set; }
        public string CUSTOMCOMBO5 { get; set; }
        public string CUSTOMCOMBO6 { get; set; }
        public string CUSTOMCOMBO7 { get; set; }
        public string CUSTOMCOMBO8 { get; set; }
        public string CUSTOMCOMBO9 { get; set; }
        public string CUSTOMLONG0 { get; set; }
        public string CUSTOMLONG1 { get; set; }
        public string CUSTOMNOTE { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE0 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE1 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE3 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE4 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC0 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC1 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC2 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC3 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC4 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL0 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL1 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL2 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL3 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL4 { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> LASTMODIFIEDTIME { get; set; }
        public string LASTMODIFIEDUSER { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
    }
}
