//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_REASONCODEMASTER
    {
        public string RSN_CODE { get; set; }
        public string TYPE1 { get; set; }
        public string DESC1 { get; set; }
        public string USER1 { get; set; }
        public string SUBACCOUNT { get; set; }
        public string DOMAIN { get; set; }
        public string COSTCENTER { get; set; }
        public string GLACCOUNT { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
