//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_ZKBUD_DET
    {
        public string zkbud_domain { get; set; }
        public string zkbud_site { get; set; }
        public string zkbud_bc_id { get; set; }
        public string zkbud_predefine { get; set; }
        public string zkbud_part { get; set; }
        public string zkbud_lot { get; set; }
        public string zkbud_ref { get; set; }
        public Nullable<decimal> zkbud_qty { get; set; }
        public string zkbud_pallet_id { get; set; }
        public string zkbud_tr_type { get; set; }
        public string zkbud_order { get; set; }
        public string zkbud_lnid { get; set; }
        public Nullable<System.DateTime> zkbud_date { get; set; }
        public string zkbud_remark { get; set; }
        public string zkbud_userid { get; set; }
        public Nullable<System.DateTime> zkbud_mod_date { get; set; }
        public string zkbud_batch_no { get; set; }
        public string zkbud_supp_ref { get; set; }
        public string zkbud_pack_no { get; set; }
        public string zkbud_shipper_no { get; set; }
        public string zkbud__chr01 { get; set; }
        public string zkbud__chr02 { get; set; }
        public string zkbud__chr03 { get; set; }
        public string zkbud__chr04 { get; set; }
        public string zkbud__chr05 { get; set; }
        public string zkbud__chr06 { get; set; }
        public string zkbud__chr07 { get; set; }
        public string zkbud__chr08 { get; set; }
        public string zkbud__chr09 { get; set; }
        public string zkbud__chr10 { get; set; }
        public Nullable<int> zkbud__int01 { get; set; }
        public Nullable<int> zkbud__int02 { get; set; }
        public Nullable<int> zkbud__int03 { get; set; }
        public Nullable<int> zkbud__int04 { get; set; }
        public Nullable<int> zkbud__int05 { get; set; }
        public Nullable<int> zkbud__int06 { get; set; }
        public Nullable<int> zkbud__int07 { get; set; }
        public Nullable<int> zkbud__int08 { get; set; }
        public Nullable<int> zkbud__int09 { get; set; }
        public Nullable<int> zkbud__int10 { get; set; }
        public Nullable<decimal> zkbud__dec01 { get; set; }
        public Nullable<decimal> zkbud__dec02 { get; set; }
        public Nullable<decimal> zkbud__dec03 { get; set; }
        public Nullable<decimal> zkbud__dec04 { get; set; }
        public Nullable<decimal> zkbud__dec05 { get; set; }
        public Nullable<decimal> zkbud__dec06 { get; set; }
        public Nullable<decimal> zkbud__dec07 { get; set; }
        public Nullable<decimal> zkbud__dec08 { get; set; }
        public Nullable<decimal> zkbud__dec09 { get; set; }
        public Nullable<decimal> zkbud__dec10 { get; set; }
        public Nullable<System.DateTime> zkbud__dte01 { get; set; }
        public Nullable<System.DateTime> zkbud__dte02 { get; set; }
        public Nullable<System.DateTime> zkbud__dte03 { get; set; }
        public Nullable<System.DateTime> zkbud__dte04 { get; set; }
        public Nullable<System.DateTime> zkbud__dte05 { get; set; }
        public Nullable<System.DateTime> zkbud__dte06 { get; set; }
        public Nullable<System.DateTime> zkbud__dte07 { get; set; }
        public Nullable<System.DateTime> zkbud__dte08 { get; set; }
        public Nullable<System.DateTime> zkbud__dte09 { get; set; }
        public Nullable<System.DateTime> zkbud__dte10 { get; set; }
        public string zkbud__log01 { get; set; }
        public string zkbud__log02 { get; set; }
        public string zkbud__log03 { get; set; }
        public string zkbud__log04 { get; set; }
        public string zkbud__log05 { get; set; }
        public string zkbud_transno { get; set; }
        public string zkbud_loc { get; set; }
        public string zkbud_cust { get; set; }
        public string zkbud_pallet_type { get; set; }
        public string zkbud_time { get; set; }
    }
}
