//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_BUSINESSRELATION
    {
        public string BUSINESSRELATIONCODE { get; set; }
        public string BUSINESSRELATIONNAME1 { get; set; }
        public string BUSINESSRELATIONNAME2 { get; set; }
        public string BUSINESSRELATIONNAME3 { get; set; }
        public string BUSINESSRELATIONSEARCHNAME { get; set; }
        public string BUSINESSRELATIONICCODE { get; set; }
        public decimal BUSINESSRELATION_ID { get; set; }
        public Nullable<decimal> CORPORATEGROUP_ID { get; set; }
        public Nullable<decimal> LNG_ID { get; set; }
        public Nullable<decimal> OBSOLETESALESPRICELIST_ID { get; set; }
        public Nullable<decimal> OBSOLETEPURCHPRICELIST_ID { get; set; }
        public Nullable<decimal> OBSOLETECOSTPRICELIST_ID { get; set; }
        public string BUSINESSRELATIONISACTIVE { get; set; }
        public string BUSINESSRELATIONISINTERCO { get; set; }
        public string BUSINESSRELATIONISINCOMP { get; set; }
        public string BUSINESSRELATIONISCOMPENS { get; set; }
        public string BUSINESSRELATIONAVRCODE { get; set; }
        public string BUSINESSRELATIONEANCODE { get; set; }
        public string BUSINESSRELATIONISTAXREP { get; set; }
        public string BUSINESSRELATIONISLASTFILL { get; set; }
        public string BUSINESSRELATIONNAMECTRL { get; set; }
        public string CUSTOMSHORT0 { get; set; }
        public string CUSTOMSHORT1 { get; set; }
        public string CUSTOMSHORT2 { get; set; }
        public string CUSTOMSHORT3 { get; set; }
        public string CUSTOMSHORT4 { get; set; }
        public string CUSTOMSHORT5 { get; set; }
        public string CUSTOMSHORT6 { get; set; }
        public string CUSTOMSHORT7 { get; set; }
        public string CUSTOMSHORT8 { get; set; }
        public string CUSTOMSHORT9 { get; set; }
        public string CUSTOMCOMBO0 { get; set; }
        public string CUSTOMCOMBO1 { get; set; }
        public string CUSTOMCOMBO2 { get; set; }
        public string CUSTOMCOMBO3 { get; set; }
        public string CUSTOMCOMBO4 { get; set; }
        public string CUSTOMCOMBO5 { get; set; }
        public string CUSTOMCOMBO6 { get; set; }
        public string CUSTOMCOMBO7 { get; set; }
        public string CUSTOMCOMBO8 { get; set; }
        public string CUSTOMCOMBO9 { get; set; }
        public string CUSTOMLONG0 { get; set; }
        public string CUSTOMLONG1 { get; set; }
        public string CUSTOMNOTE { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE0 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE1 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE3 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE4 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC0 { get; set; }
        public Nullable<decimal> CUSTOMINTEGER1 { get; set; }
        public Nullable<decimal> CUSTOMINTEGER2 { get; set; }
        public Nullable<decimal> CUSTOMINTEGER3 { get; set; }
        public Nullable<decimal> CUSTOMINTEGER4 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL0 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL1 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL2 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL3 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL4 { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> LASTMODIFIEDTIME { get; set; }
        public string LASTMODIFIEDUSER { get; set; }
        public Nullable<decimal> DOMAIN_ID { get; set; }
        public string BUSINESSRELATIONISDOMRESTR { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string BUSINESSRELATIONORGTYPE { get; set; }
        public string BUSINESSRELATIONCOMREGISTERNBR { get; set; }
        public string BUSINESSRELATIONINSTNBR { get; set; }
        public string BUSINESSRELATIONINSTCODE { get; set; }
        public string CUSTOMSHORT10 { get; set; }
        public string CUSTOMSHORT11 { get; set; }
        public string CUSTOMSHORT12 { get; set; }
        public string CUSTOMSHORT13 { get; set; }
        public string CUSTOMSHORT14 { get; set; }
        public string CUSTOMCOMBO10 { get; set; }
        public string CUSTOMCOMBO11 { get; set; }
        public string CUSTOMCOMBO12 { get; set; }
        public string CUSTOMCOMBO13 { get; set; }
        public string CUSTOMCOMBO14 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE5 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE6 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE7 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE8 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE9 { get; set; }
        public string RowActiveFlag { get; set; }
        public Nullable<System.DateTime> RowCreateDateTime { get; set; }
        public Nullable<System.DateTime> RowUpdateDateTime { get; set; }
    }
}
