//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_PTRE_MSTR
    {
        public string ptre_part { get; set; }
        public string ptre_qty { get; set; }
        public string ptre_rep_part { get; set; }
        public string ptre_rep_qty { get; set; }
        public string ptre_site { get; set; }
        public string ptre_cust { get; set; }
        public bool ptre_include { get; set; }
        public System.DateTime ptre_eff_date { get; set; }
        public string ptre_cmtindx { get; set; }
        public string ptre_pco { get; set; }
        public bool ptre_auto_accept { get; set; }
        public System.DateTime ptre_mod_date { get; set; }
        public string ptre_mod_userid { get; set; }
        public string ptre_user1 { get; set; }
        public string ptre_user2 { get; set; }
        public string ptre_userd01 { get; set; }
        public string ptre_useri01 { get; set; }
        public bool ptre_userl01 { get; set; }
        public Nullable<System.DateTime> ptre_usert01 { get; set; }
        public string ptre__qadc01 { get; set; }
        public string ptre__qadc02 { get; set; }
        public string ptre__qadd01 { get; set; }
        public string ptre__qadi01 { get; set; }
        public bool ptre__qadl01 { get; set; }
        public Nullable<System.DateTime> ptre__qadt01 { get; set; }
        public string ptre_round_qty { get; set; }
        public string ptre_ref { get; set; }
        public string ptre_type { get; set; }
        public bool ptre_default { get; set; }
        public Nullable<System.DateTime> ptre_end_date { get; set; }
        public string ptre_preference { get; set; }
        public string ptre_domain { get; set; }
        public string oid_ptre_det { get; set; }
        public string ptre_schd_chg_qty { get; set; }
    }
}
