//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_CREDITOR
    {
        public decimal CREDITOR_ID { get; set; }
        public Nullable<decimal> NORMALPAYMENTCONDITION_ID { get; set; }
        public Nullable<decimal> BUSINESSRELATION_ID { get; set; }
        public string CREDITORISACTIVE { get; set; }
        public Nullable<decimal> SHAREDSET_ID { get; set; }
        public Nullable<decimal> INVCONTROLGLPROFILE_ID { get; set; }
        public Nullable<decimal> CNCONTROLGLPROFILE_ID { get; set; }
        public Nullable<decimal> DIVISIONPROFILE_ID { get; set; }
        public Nullable<decimal> PURCHASECODE_ID { get; set; }
        public Nullable<decimal> REASON_ID { get; set; }
        public Nullable<decimal> BLWIGROUP_ID { get; set; }
        public Nullable<decimal> DELIVERYCOND_ID { get; set; }
        public Nullable<decimal> CURRENCY_ID { get; set; }
        public Nullable<decimal> PAYMENTGROUP_ID { get; set; }
        public Nullable<decimal> PURCHASEGLPROFILE_ID { get; set; }
        public Nullable<decimal> CREDITORTYPE_ID { get; set; }
        public Nullable<decimal> PURCHASETYPE_ID { get; set; }
        public Nullable<decimal> PREPAYCONTROLGLPROFILE_ID { get; set; }
        public string CREDITORCODE { get; set; }
        public string VATDELIVERYTYPE { get; set; }
        public string VATPERCENTAGELEVEL { get; set; }
        public string CREDITORISSENDREMITTANCE { get; set; }
        public string CREDITORISINDIVIDUALPAYMNT { get; set; }
        public string CREDITORISTAXABLE { get; set; }
        public string CREDITORISTAXINCITY { get; set; }
        public string CREDITORISTAXINCLUDED { get; set; }
        public string CREDITORTAXIDFEDERAL { get; set; }
        public string CREDITORTAXIDSTATE { get; set; }
        public string CREDITORTAXIDMISC1 { get; set; }
        public string CREDITORTAXIDMISC2 { get; set; }
        public string CREDITORTAXIDMISC3 { get; set; }
        public Nullable<decimal> CREDITORTAXDECLARATION { get; set; }
        public string CREDITORISTAXREPORT { get; set; }
        public string CREDITORDBNUMERIC { get; set; }
        public string CREDITORCOCNUMERIC { get; set; }
        public string CREDITORTIDNOTICE { get; set; }
        public string CREDITORDEBTORNUMERIC { get; set; }
        public string CREDITORISTAXCONFIRMED { get; set; }
        public string CREDITORCOMMENTNOTE { get; set; }
        public string TXZTAXZONE { get; set; }
        public string TXCLTAXCLS { get; set; }
        public string TXUTAXUSAGE { get; set; }
        public string CUSTOMSHORT0 { get; set; }
        public string CUSTOMSHORT1 { get; set; }
        public string CUSTOMSHORT2 { get; set; }
        public string CUSTOMSHORT3 { get; set; }
        public string CUSTOMSHORT4 { get; set; }
        public string CUSTOMSHORT5 { get; set; }
        public string CUSTOMSHORT6 { get; set; }
        public string CUSTOMSHORT7 { get; set; }
        public string CUSTOMSHORT8 { get; set; }
        public string CUSTOMSHORT9 { get; set; }
        public string CUSTOMCOMBO0 { get; set; }
        public string CUSTOMCOMBO1 { get; set; }
        public string CUSTOMCOMBO2 { get; set; }
        public string CUSTOMCOMBO3 { get; set; }
        public string CUSTOMCOMBO4 { get; set; }
        public string CUSTOMCOMBO5 { get; set; }
        public string CUSTOMCOMBO6 { get; set; }
        public string CUSTOMCOMBO7 { get; set; }
        public string CUSTOMCOMBO8 { get; set; }
        public string CUSTOMCOMBO9 { get; set; }
        public string CUSTOMLONG0 { get; set; }
        public string CUSTOMLONG1 { get; set; }
        public string CUSTOMNOTE { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE0 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE1 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE3 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE4 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC0 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC1 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC2 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC3 { get; set; }
        public Nullable<decimal> CUSTOMNUMERIC4 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL0 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL1 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL2 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL3 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL4 { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> LASTMODIFIEDTIME { get; set; }
        public string LASTMODIFIEDUSER { get; set; }
        public Nullable<decimal> WHTCERTFORMAT_ID { get; set; }
        public string CREDITORISWHT { get; set; }
        public string CREDITORTAXIDFISCALCODE { get; set; }
        public string CREDITORFOREIGNFISCALCODE { get; set; }
        public Nullable<System.DateTime> CREDITORBIRTHDATE { get; set; }
        public string CREDITORBIRTHCITY { get; set; }
        public Nullable<decimal> FINCHGGLPROFILE_ID { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string CUSTOMSHORT10 { get; set; }
        public string CUSTOMSHORT11 { get; set; }
        public string CUSTOMSHORT12 { get; set; }
        public string CUSTOMSHORT13 { get; set; }
        public string CUSTOMSHORT14 { get; set; }
        public string CUSTOMSHORT15 { get; set; }
        public string CUSTOMSHORT16 { get; set; }
        public string CUSTOMSHORT17 { get; set; }
        public string CUSTOMSHORT18 { get; set; }
        public string CUSTOMSHORT19 { get; set; }
        public string CUSTOMCOMBO10 { get; set; }
        public string CUSTOMCOMBO11 { get; set; }
        public string CUSTOMCOMBO12 { get; set; }
        public string CUSTOMCOMBO13 { get; set; }
        public string CUSTOMCOMBO14 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL5 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL6 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL7 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL8 { get; set; }
        public Nullable<decimal> CUSTOMDECIMAL9 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE5 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE6 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE7 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE8 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE9 { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public string AddressStreet1 { get; set; }
        public string AddressStreet2 { get; set; }
        public string AddressStreet3 { get; set; }
        public string AddressZip { get; set; }
        public string AddressCity { get; set; }
        public string AddressName { get; set; }
        public string CountryIsActive { get; set; }
        public string PurchaseTypeIsActive { get; set; }
        public string AddressSearchName { get; set; }
        public string AddressTelephone { get; set; }
        public string AddressEMail { get; set; }
        public string AddressWebSite { get; set; }
        public string AddressFax { get; set; }
        public string CountryDescription { get; set; }
        public string CountryCode { get; set; }
        public string AddressTypeCode { get; set; }
        public string PurchaseTypeCode { get; set; }
        public string PurchaseTypeDescription { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ADDRESS_ID { get; set; }
    }
}
