//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_LS_MSTR
    {
        public string type { get; set; }
        public string addr { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public string qadc01 { get; set; }
        public string app_owner { get; set; }
        public string dec01 { get; set; }
        public string dec02 { get; set; }
        public string int01 { get; set; }
        public string int02 { get; set; }
        public Nullable<bool> log01 { get; set; }
        public Nullable<bool> log02 { get; set; }
        public Nullable<System.DateTime> dte01 { get; set; }
        public Nullable<System.DateTime> dte02 { get; set; }
        public string qadc02 { get; set; }
        public string qadc03 { get; set; }
        public string qadc04 { get; set; }
        public string qadd01 { get; set; }
        public string qadd02 { get; set; }
        public string qadi01 { get; set; }
        public string qadi02 { get; set; }
        public Nullable<bool> qadl01 { get; set; }
        public Nullable<bool> qadl02 { get; set; }
        public Nullable<System.DateTime> qadt01 { get; set; }
        public Nullable<System.DateTime> qadt02 { get; set; }
        public string domain { get; set; }
        public string oid_ls_mstr { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
