//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_CODE_MSTR
    {
        public string CODE_FLDNAME { get; set; }
        public string CODE_VALUE { get; set; }
        public string CODE_CMMT { get; set; }
        public string CODE_USER1 { get; set; }
        public string CODE_USER2 { get; set; }
        public string CODE_DESC { get; set; }
        public string CODE_QADC01 { get; set; }
        public string CODE_DOMAIN { get; set; }
        public decimal OID_CODE_MSTR { get; set; }
        public string CODE_GROUP { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public string ROWACTIVEFLAG { get; set; }
    }
}
