//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SAFSTRUCTURELINK
    {
        public decimal SAFSTRUCTURELINK_ID { get; set; }
        public Nullable<decimal> SAFSTRUCTURE_ID { get; set; }
        public Nullable<decimal> GL_ID { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public Nullable<decimal> COSTCENTRE_ID { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> LASTMODIFIEDTIME { get; set; }
        public string LASTMODIFIEDUSER { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public Nullable<System.DateTime> RowCreateDateTime { get; set; }
        public Nullable<System.DateTime> RowUpdateDateTime { get; set; }
    }
}
