//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_CM_MSTR
    {
        public string addr { get; set; }
        public string ship { get; set; }
        public string type { get; set; }
        public string cr_terms { get; set; }
        public string xslspsn { get; set; }
        public string qadi01 { get; set; }
        public string pr_list { get; set; }
        public string disc_pct { get; set; }
        public Nullable<bool> partial { get; set; }
        public Nullable<bool> stmt { get; set; }
        public Nullable<bool> dun { get; set; }
        public Nullable<bool> fin { get; set; }
        public string ar_acct { get; set; }
        public string ar_cc { get; set; }
        public string qadc07 { get; set; }
        public string qadc01 { get; set; }
        public string stmt_cyc { get; set; }
        public string shipvia { get; set; }
        public string rmks { get; set; }
        public string resale { get; set; }
        public string region { get; set; }
        public string qad04 { get; set; }
        public string sort { get; set; }
        public string balance { get; set; }
        public Nullable<bool> taxable { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string xslspsn2 { get; set; }
        public string qadi02 { get; set; }
        public string avg_pay { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public string curr { get; set; }
        public string lang { get; set; }
        public string db { get; set; }
        public Nullable<bool> cr_hold { get; set; }
        public string cr_rating { get; set; }
        public string high_cr { get; set; }
        public Nullable<System.DateTime> high_date { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public string invoices { get; set; }
        public Nullable<System.DateTime> fin_date { get; set; }
        public Nullable<bool> qad06 { get; set; }
        public string fst_id { get; set; }
        public string pst_id { get; set; }
        public Nullable<bool> pst { get; set; }
        public Nullable<bool> tax_in { get; set; }
        public string site { get; set; }
        public string @class { get; set; }
        public string taxc { get; set; }
        public string bill { get; set; }
        public string chr01 { get; set; }
        public string chr02 { get; set; }
        public string chr03 { get; set; }
        public string chr04 { get; set; }
        public string chr05 { get; set; }
        public string chr06 { get; set; }
        public string chr07 { get; set; }
        public string chr08 { get; set; }
        public string chr09 { get; set; }
        public string chr10 { get; set; }
        public Nullable<System.DateTime> dte01 { get; set; }
        public Nullable<System.DateTime> dte02 { get; set; }
        public string dec01 { get; set; }
        public string dec02 { get; set; }
        public Nullable<bool> log01 { get; set; }
        public string qadc02 { get; set; }
        public string fr_list { get; set; }
        public string fr_terms { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> mod_date { get; set; }
        public string conrep_logic { get; set; }
        public string slspsn { get; set; }
        public string fr_min_wt { get; set; }
        public string drft_bal { get; set; }
        public string lc_bal { get; set; }
        public string pr_list2 { get; set; }
        public Nullable<bool> fix_pr { get; set; }
        public Nullable<System.DateTime> cr_update { get; set; }
        public Nullable<System.DateTime> cr_review { get; set; }
        public string coll_mthd { get; set; }
        public string drft_min { get; set; }
        public string drft_max { get; set; }
        public bool drft_disc { get; set; }
        public bool drft_apv { get; set; }
        public Nullable<bool> @internal { get; set; }
        public string svc_list { get; set; }
        public Nullable<bool> po_reqd { get; set; }
        public string serv_terms { get; set; }
        public string cr_limit { get; set; }
        public string promo { get; set; }
        public bool btb_cr { get; set; }
        public string btb_type { get; set; }
        public string ship_lt { get; set; }
        public bool btb_mthd { get; set; }
        public string ex_ratetype { get; set; }
        public string disc_comb { get; set; }
        public string scurr { get; set; }
        public string qadc03 { get; set; }
        public string qadc04 { get; set; }
        public string qadc05 { get; set; }
        public string qadc06 { get; set; }
        public string qadd01 { get; set; }
        public string qadd02 { get; set; }
        public Nullable<bool> qadl01 { get; set; }
        public Nullable<bool> qadl02 { get; set; }
        public Nullable<bool> qadl03 { get; set; }
        public Nullable<bool> qadl04 { get; set; }
        public Nullable<System.DateTime> qadt01 { get; set; }
        public Nullable<System.DateTime> qadt02 { get; set; }
        public string qadi03 { get; set; }
        public string qadi04 { get; set; }
        public string ar_sub { get; set; }
        public string sic { get; set; }
        public string pay_method { get; set; }
        public bool submit_prop { get; set; }
        public string bank { get; set; }
        public string domain { get; set; }
        public string oid_cm_mstr { get; set; }
        public string rss_cal_option { get; set; }
        public string oid_btr_mstr { get; set; }
        public bool active { get; set; }
        public bool datacomplete { get; set; }
        public string daybookset { get; set; }
        public string misc3_id { get; set; }
        public string misc2_id { get; set; }
        public string misc1_id { get; set; }
        public string gst_id { get; set; }
        public string tax_usage { get; set; }
        public string tax_zone { get; set; }
        public bool tax_in_city { get; set; }
        public bool sb_auto_payment { get; set; }
    }
}
