//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_CustomerView
    {
        public string Debtor_ID { get; set; }
        public string SharedSet_ID { get; set; }
        public string InvControlGLProfile_ID { get; set; }
        public string CnControlGLProfile_ID { get; set; }
        public string FinChgGLProfile_ID { get; set; }
        public string NormalPaymentCondition_ID { get; set; }
        public string BusinessRelation_ID { get; set; }
        public string Currency_ID { get; set; }
        public string DivisionProfile_ID { get; set; }
        public string SalesCode_ID { get; set; }
        public string VatDeliveryType { get; set; }
        public string Reason_ID { get; set; }
        public string BLWIGroup_ID { get; set; }
        public string DeliveryCond_ID { get; set; }
        public string PaymentGroup_ID { get; set; }
        public string ObsoletePreInvGroup_ID { get; set; }
        public string SalesAccountGLProfile_ID { get; set; }
        public string BillToDebtor_ID { get; set; }
        public string DebtorType_ID { get; set; }
        public string DebtorCreditRating_ID { get; set; }
        public string PrePayControlGLProfile_ID { get; set; }
        public string DebtorCode { get; set; }
        public bool DebtorIsActive { get; set; }
        public string VatPercentageLevel { get; set; }
        public bool DebtorIsPrintStatement { get; set; }
        public bool DebtorIsPrintReminder { get; set; }
        public string DomiciliationNumber { get; set; }
        public bool DebtorIsTaxable { get; set; }
        public bool DebtorIsTaxInCity { get; set; }
        public bool DebtorIsTaxIncluded { get; set; }
        public string DebtorTaxIDFederal { get; set; }
        public string DebtorTaxIDState { get; set; }
        public string DebtorTaxIDMisc1 { get; set; }
        public string DebtorTaxIDMisc2 { get; set; }
        public string DebtorTaxIDMisc3 { get; set; }
        public string DebtorTaxDeclaration { get; set; }
        public bool DebtorIsFixedCredLim { get; set; }
        public string DebtorFixedCredLimTC { get; set; }
        public bool DebtorIsTurnOverCredLim { get; set; }
        public string DebtorPercTurnOverCredLim { get; set; }
        public bool DebtorIsMaxDaysDueCredLim { get; set; }
        public string DebtorMaxNumDaysCredLim { get; set; }
        public bool DebtorIsInclOpenItmCredLim { get; set; }
        public bool ObsoleteInclPreInvCredLim { get; set; }
        public bool DebtorIsInclSOCredLim { get; set; }
        public bool DebtorIsInclDraftCredLim { get; set; }
        public bool DebtorIsCheckBefSOCredLim { get; set; }
        public bool DebtorIsCheckAftSOCredLim { get; set; }
        public bool ObsoleteCheckBefPICredLim { get; set; }
        public bool ObsoleteCheckAftPICredLim { get; set; }
        public bool DebtorIsCheckBefDICredLim { get; set; }
        public bool DebtorIsCheckAftDICredLim { get; set; }
        public string DebtorPercWarningCredLim { get; set; }
        public bool DebtorIsOverruleSOCredLim { get; set; }
        public bool ObsoleteOverrulePICredLim { get; set; }
        public bool DebtorIsOverruleDICredLim { get; set; }
        public bool DebtorIsLockedCredLim { get; set; }
        public bool DebtorIsToBeLockedCredLim { get; set; }
        public bool DebtorIsWithPreInvGroup { get; set; }
        public bool ObsoleteGroupingSOOnPreInv { get; set; }
        public bool DebtorIsInvoiceByAuth { get; set; }
        public string DebtorDBNumber { get; set; }
        public bool DebtorIsFinanceCharge { get; set; }
        public string DebtorStatementCycle { get; set; }
        public Nullable<System.DateTime> DebtorLastPayment { get; set; }
        public Nullable<System.DateTime> DebtorLastSale { get; set; }
        public string DebtorHighCredit { get; set; }
        public Nullable<System.DateTime> DebtorHighCreditDate { get; set; }
        public Nullable<System.DateTime> DebtorLastCreditReview { get; set; }
        public Nullable<System.DateTime> DebtorLastCreditUpdate { get; set; }
        public string DebtorCommentNote { get; set; }
        public string DebtorSalesOrderBalance { get; set; }
        public Nullable<System.DateTime> DebtorLastFinChargeDate { get; set; }
        public string DebtorTotalDaysLate { get; set; }
        public string DebtorTotalNbrOfInvoices { get; set; }
        public string TxzTaxZone { get; set; }
        public string TxclTaxCls { get; set; }
        public string TxuTaxUsage { get; set; }
        public string CustomShort0 { get; set; }
        public string CustomShort1 { get; set; }
        public string CustomShort2 { get; set; }
        public string CustomShort3 { get; set; }
        public string CustomShort4 { get; set; }
        public string CustomShort5 { get; set; }
        public string CustomShort6 { get; set; }
        public string CustomShort7 { get; set; }
        public string CustomShort8 { get; set; }
        public string CustomShort9 { get; set; }
        public string CustomCombo0 { get; set; }
        public string CustomCombo1 { get; set; }
        public string CustomCombo2 { get; set; }
        public string CustomCombo3 { get; set; }
        public string CustomCombo4 { get; set; }
        public string CustomCombo5 { get; set; }
        public string CustomCombo6 { get; set; }
        public string CustomCombo7 { get; set; }
        public string CustomCombo8 { get; set; }
        public string CustomCombo9 { get; set; }
        public string CustomLong0 { get; set; }
        public string CustomLong1 { get; set; }
        public string CustomNote { get; set; }
        public Nullable<System.DateTime> CustomDate0 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public string CustomInteger0 { get; set; }
        public string CustomInteger1 { get; set; }
        public string CustomInteger2 { get; set; }
        public string CustomInteger3 { get; set; }
        public string CustomInteger4 { get; set; }
        public string CustomDecimal0 { get; set; }
        public string CustomDecimal1 { get; set; }
        public string CustomDecimal2 { get; set; }
        public string CustomDecimal3 { get; set; }
        public string CustomDecimal4 { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedTime { get; set; }
        public string LastModifiedUser { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public string QADD01 { get; set; }
        public string DeductionCtrlGLProfile_ID { get; set; }
        public string CustomShort10 { get; set; }
        public string CustomShort11 { get; set; }
        public string CustomShort12 { get; set; }
        public string CustomShort13 { get; set; }
        public string CustomShort14 { get; set; }
        public string CustomShort15 { get; set; }
        public string CustomShort16 { get; set; }
        public string CustomShort17 { get; set; }
        public string CustomShort18 { get; set; }
        public string CustomShort19 { get; set; }
        public string CustomCombo10 { get; set; }
        public string CustomCombo11 { get; set; }
        public string CustomCombo12 { get; set; }
        public string CustomCombo13 { get; set; }
        public string CustomCombo14 { get; set; }
        public string CustomDecimal5 { get; set; }
        public string CustomDecimal6 { get; set; }
        public string CustomDecimal7 { get; set; }
        public string CustomDecimal8 { get; set; }
        public string CustomDecimal9 { get; set; }
        public Nullable<System.DateTime> CustomDate5 { get; set; }
        public Nullable<System.DateTime> CustomDate6 { get; set; }
        public Nullable<System.DateTime> CustomDate7 { get; set; }
        public Nullable<System.DateTime> CustomDate8 { get; set; }
        public Nullable<System.DateTime> CustomDate9 { get; set; }
    }
}
