//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAD_SAFCONCEPT
    {
        public decimal SAFCONCEPT_ID { get; set; }
        public string SAFCONCEPTCODE { get; set; }
        public string SAFCONCEPTDESCRIPTION { get; set; }
        public string SAFCONCEPTISACTIVE { get; set; }
        public string SAFCONCEPTISSYSTEM { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public Nullable<decimal> LASTMODIFIEDTIME { get; set; }
        public string LASTMODIFIEDUSER { get; set; }
        public string QADC01 { get; set; }
        public string QADC02 { get; set; }
        public Nullable<System.DateTime> QADT01 { get; set; }
        public Nullable<decimal> QADD01 { get; set; }
        public string ROWACTIVEFLAG { get; set; }
        public Nullable<System.DateTime> ROWCREATEDATETIME { get; set; }
        public Nullable<System.DateTime> ROWUPDATEDATETIME { get; set; }
    }
}
