//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPIs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THAPP_TCOMMON_DEVEntities : DbContext
    {
        public THAPP_TCOMMON_DEVEntities()
            : base("name=THAPP_TCOMMON_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CM_APPLICATIONS> CM_APPLICATIONS { get; set; }
        public virtual DbSet<CM_APPS_ATTR> CM_APPS_ATTR { get; set; }
        public virtual DbSet<CM_APPS_FUNCTIONS> CM_APPS_FUNCTIONS { get; set; }
        public virtual DbSet<CM_APPS_ROLES> CM_APPS_ROLES { get; set; }
        public virtual DbSet<CM_ATTRTYPE_MSTR> CM_ATTRTYPE_MSTR { get; set; }
        public virtual DbSet<CM_DOMAIN> CM_DOMAIN { get; set; }
        public virtual DbSet<CM_DOMAIN_MSTR> CM_DOMAIN_MSTR { get; set; }
        public virtual DbSet<CM_FACILITY> CM_FACILITY { get; set; }
        public virtual DbSet<CM_NN> CM_NN { get; set; }
        public virtual DbSet<CM_RBAC> CM_RBAC { get; set; }
        public virtual DbSet<CM_SITE> CM_SITE { get; set; }
        public virtual DbSet<CM_SITES_MSTR> CM_SITES_MSTR { get; set; }
        public virtual DbSet<CM_USERS_AUTHORIZE> CM_USERS_AUTHORIZE { get; set; }
        public virtual DbSet<CM_VALUETYPE_MSTR> CM_VALUETYPE_MSTR { get; set; }
        public virtual DbSet<QAD_AD_MSTR> QAD_AD_MSTR { get; set; }
        public virtual DbSet<QAD_BUSINESSRELATION> QAD_BUSINESSRELATION { get; set; }
        public virtual DbSet<QAD_CM_MSTR> QAD_CM_MSTR { get; set; }
        public virtual DbSet<QAD_CODE_MSTR> QAD_CODE_MSTR { get; set; }
        public virtual DbSet<QAD_CREDITOR> QAD_CREDITOR { get; set; }
        public virtual DbSet<QAD_CustomerItem> QAD_CustomerItem { get; set; }
        public virtual DbSet<QAD_CustomerShipTo> QAD_CustomerShipTo { get; set; }
        public virtual DbSet<QAD_CustomerView> QAD_CustomerView { get; set; }
        public virtual DbSet<QAD_DEBTOR> QAD_DEBTOR { get; set; }
        public virtual DbSet<QAD_FAD_DET> QAD_FAD_DET { get; set; }
        public virtual DbSet<QAD_FIXEDASSETLOC> QAD_FIXEDASSETLOC { get; set; }
        public virtual DbSet<QAD_FIXEDASSETMASTER> QAD_FIXEDASSETMASTER { get; set; }
        public virtual DbSet<QAD_GL> QAD_GL { get; set; }
        public virtual DbSet<QAD_HFMCustomerShipTo> QAD_HFMCustomerShipTo { get; set; }
        public virtual DbSet<QAD_INVENTORYLOCMASTER> QAD_INVENTORYLOCMASTER { get; set; }
        public virtual DbSet<QAD_ITEMCOST> QAD_ITEMCOST { get; set; }
        public virtual DbSet<QAD_ItemCost_STG> QAD_ItemCost_STG { get; set; }
        public virtual DbSet<QAD_ITEMMASTER> QAD_ITEMMASTER { get; set; }
        public virtual DbSet<QAD_ITEMNUMBER> QAD_ITEMNUMBER { get; set; }
        public virtual DbSet<QAD_ITEMPACKAGING> QAD_ITEMPACKAGING { get; set; }
        public virtual DbSet<QAD_ITEMPLANNING> QAD_ITEMPLANNING { get; set; }
        public virtual DbSet<QAD_ItemReplacement> QAD_ItemReplacement { get; set; }
        public virtual DbSet<QAD_LS_CustomerShipTo> QAD_LS_CustomerShipTo { get; set; }
        public virtual DbSet<QAD_LS_MSTR> QAD_LS_MSTR { get; set; }
        public virtual DbSet<QAD_PC_MSTR> QAD_PC_MSTR { get; set; }
        public virtual DbSet<QAD_ProductionLineDetail> QAD_ProductionLineDetail { get; set; }
        public virtual DbSet<QAD_ProjectCode> QAD_ProjectCode { get; set; }
        public virtual DbSet<QAD_PTRE_MSTR> QAD_PTRE_MSTR { get; set; }
        public virtual DbSet<QAD_REASONCODEMASTER> QAD_REASONCODEMASTER { get; set; }
        public virtual DbSet<QAD_SAF> QAD_SAF { get; set; }
        public virtual DbSet<QAD_SAFCONCEPT> QAD_SAFCONCEPT { get; set; }
        public virtual DbSet<QAD_SAFSTRUCTURE> QAD_SAFSTRUCTURE { get; set; }
        public virtual DbSet<QAD_SAFSTRUCTURELINE> QAD_SAFSTRUCTURELINE { get; set; }
        public virtual DbSet<QAD_SAFSTRUCTURELINK> QAD_SAFSTRUCTURELINK { get; set; }
        public virtual DbSet<QAD_SCHD_DET> QAD_SCHD_DET { get; set; }
        public virtual DbSet<QAD_SIOP_ADM_DET> QAD_SIOP_ADM_DET { get; set; }
        public virtual DbSet<QAD_SIOP_AMD_DET> QAD_SIOP_AMD_DET { get; set; }
        public virtual DbSet<QAD_SIOP_AMK> QAD_SIOP_AMK { get; set; }
        public virtual DbSet<QAD_SIOP_AMK_DET> QAD_SIOP_AMK_DET { get; set; }
        public virtual DbSet<QAD_SIOP_AVS_DET> QAD_SIOP_AVS_DET { get; set; }
        public virtual DbSet<QAD_SupplierView> QAD_SupplierView { get; set; }
        public virtual DbSet<QAD_UM> QAD_UM { get; set; }
        public virtual DbSet<QAD_VDMASTER> QAD_VDMASTER { get; set; }
        public virtual DbSet<QAD_ZKBUD_DET> QAD_ZKBUD_DET { get; set; }
    }
}
