//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_ATTRTYPE_MSTR
    {
        public string ATTRTYPE_CODE { get; set; }
        public string TITLE { get; set; }
        public string VALUETYPE_CODE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
