//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_DOMAIN_MSTR
    {
        public string DOMAIN_CODE { get; set; }
        public string FACT_CODE { get; set; }
        public string DESC { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
