//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_USERS_AUTHORIZE
    {
        public string AUTH_CODE { get; set; }
        public string ROLE_CODE { get; set; }
        public string APP_CODE { get; set; }
        public string SITE_CODE { get; set; }
        public string DOMAIN_CODE { get; set; }
        public string FACT_CODE { get; set; }
        public string USERID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string ORG { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    }
}
