//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPPs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TAPP_TCOMMONEntities : DbContext
    {
        public TAPP_TCOMMONEntities()
            : base("name=TAPP_TCOMMONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CM_APPLICATIONS> CM_APPLICATIONS { get; set; }
        public virtual DbSet<CM_APPS_ATTR> CM_APPS_ATTR { get; set; }
        public virtual DbSet<CM_APPS_FUNCTIONS> CM_APPS_FUNCTIONS { get; set; }
        public virtual DbSet<CM_APPS_ROLES> CM_APPS_ROLES { get; set; }
        public virtual DbSet<CM_ATTRTYPE_MSTR> CM_ATTRTYPE_MSTR { get; set; }
        public virtual DbSet<CM_DOMAIN> CM_DOMAIN { get; set; }
        public virtual DbSet<CM_DOMAIN_MSTR> CM_DOMAIN_MSTR { get; set; }
        public virtual DbSet<CM_FACILITY> CM_FACILITY { get; set; }
        public virtual DbSet<CM_NN> CM_NN { get; set; }
        public virtual DbSet<CM_RBAC> CM_RBAC { get; set; }
        public virtual DbSet<CM_SITE> CM_SITE { get; set; }
        public virtual DbSet<CM_SITES_MSTR> CM_SITES_MSTR { get; set; }
        public virtual DbSet<CM_USERS_AUTHORIZE> CM_USERS_AUTHORIZE { get; set; }
        public virtual DbSet<CM_VALUETYPE_MSTR> CM_VALUETYPE_MSTR { get; set; }
    }
}
